# Generated by Django 5.2.17 on 2026-09-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full Name of the student', max_length=100)),
                ('register_number', models.CharField(help_text='Unique Register / Roll Number', max_length=50, unique=True)),
                ('email', models.EmailField(help_text='Unique Email Address', max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Contact Phone Number', max_length=15)),
                ('department', models.CharField(help_text='Academic Department name', max_length=100)),
                ('year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], help_text='Academic Year (1-4)')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=20)),
                ('date_of_birth', models.DateField(help_text='Date of Birth (YYYY-MM-DD)')),
                ('address', models.TextField(blank=True, default='', help_text='Residential Address')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Record Creation Timestamp')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
